---
kind: pipeline
name: Main

steps:
  - name: Tests
    pull: always
    image: python:3.6-buster
    commands:
#      - apt-get update -qq && apt-get install -yqq libimage-exiftool-perl
      - pip3 install poetry
      - poetry install
      - poetry run pytest -v

  - name: Build
    pull: always
    image: python:3.6-buster
    commands:
      - pip3 install poetry
      - poetry build

  - name: Publish
    pull: always
    image: python:3.6-buster
    failure: ignore
    environment:
      TOKEN:
        from_secret: PYPI_TOKEN
    commands:
      - pip3 install poetry
      - poetry publish --username __token__ --password $TOKEN
    when:
      branch:
        - master
